### Segmenting and clustering Neighborhoods in the city of Toronto, Canada

#### Week 3 - Assignment

This Jupyter contains my attempted solution to Question 1 of week 3 assignment in the Applied Capstone Module.

##### Submitted by: Tevin RIchard

# Question 1

#### 1.1 Import the required libraries

In [53]:
import pandas as pd
import requests

#### 1.2. Extract the required data from the wikipedia page

In [54]:
url ="https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"

#save data to variable using the .get method

wikipedia_data = requests.get(url)

#### 1.3 Load the page html text data into a pandas dataframe

In [55]:
#using the .text method to pull the text data

table_data = pd.read_html(wikipedia_data.text)

print("The loaded data is a ", type(table_data), "with ", len(table_data), "elements")

The loaded data is a  <class 'list'> with  3 elements

In [56]:
# Take a look at the data
table_data

[    Postal Code           Borough  \
 0           M1A      Not assigned
 1           M2A      Not assigned
 2           M3A        North York
 3           M4A        North York
 4           M5A  Downtown Toronto
 ..          ...               ...
 175         M5Z      Not assigned
 176         M6Z      Not assigned
 177         M7Z      Not assigned
 178         M8Z         Etobicoke
 179         M9Z      Not assigned

                                          Neighbourhood
 0                                         Not assigned
 1                                         Not assigned
 2                                            Parkwoods
 3                                     Victoria Village
 4                            Regent Park, Harbourfront
 ..                                                 ...
 175                                       Not assigned
 176                                       Not assigned
 177                                       Not assigned
 178  Mimico NW, The Queensway West, South of Bloor,...
 179                                       Not assigned

 [180 rows x 3 columns],
                                                   0   \
 0                                                NaN
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
 2                                                 NL
 3                                                  A

                                                   1   \
 0                              Canadian postal codes
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
 2                                                 NS
 3                                                  B

                                                   2    3    4    5    6    7   \
 0                                                NaN  NaN  NaN  NaN  NaN  NaN
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...  NaN  NaN  NaN  NaN  NaN
 2                                                 PE   NB   QC   QC   QC   ON
 3                                                  C    E    G    H    J    K

     8    9    10   11   12   13   14   15     16   17
 0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN  NaN
 1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN  NaN
 2   ON   ON   ON   ON   MB   SK   AB   BC  NU/NT   YT
 3    L    M    N    P    R    S    T    V      X    Y  ,
    0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15     16  17
 0  NL  NS  PE  NB  QC  QC  QC  ON  ON  ON  ON  ON  MB  SK  AB  BC  NU/NT  YT
 1   A   B   C   E   G   H   J   K   L   M   N   P   R   S   T   V      X   Y]

#### 1.4 Extract the data required (First element in the list containing our three columns)

In [57]:
# replce the list with our required data since lists are mutable
table_data = table_data[0]
table_data

,Postal Code,Borough,Neighbourhood
0,M1A,Not assigned,Not assigned
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
...,...,...,...
175,M5Z,Not assigned,Not assigned
176,M6Z,Not assigned,Not assigned
177,M7Z,Not assigned,Not assigned
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
179,M9Z,Not assigned,Not assigned

#### 1.5 Drop all the Boroughs that contain Not Assigned elements

In [58]:
df = table_data[table_data["Borough"] != "Not assigned"]
df

,Postal Code,Borough,Neighbourhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
160,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

#### 1.6 Group all the elements that have the same postal codes as a single entry

In [63]:
df = df.groupby(['Postal Code']).head()
df

,Postal Code,Borough,Neighbourhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

#### 1.7.Fix the indices

In [64]:
# reset the dataframe index
df = df.reset_index()
df

,index,Postal Code,Borough,Neighbourhood
0,0,M3A,North York,Parkwoods
1,1,M4A,North York,Victoria Village
2,2,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,3,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...,...
98,98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
99,99,M4Y,Downtown Toronto,Church and Wellesley
100,100,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
101,101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
102,102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [65]:
# replace the old index with the updated indices
df = df.drop(["index"], "columns")
df

,Postal Code,Borough,Neighbourhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

#### 1.8 Get the shape of the data set

In [70]:
print("The data frame has ", df.shape[0], "rows and ", df.shape[1], "columns")

The data frame has  103 rows and  3 columns

# Question 2

#### 2.1 Install the Geocoder library

In [71]:
pip install geocoder

Collecting geocoderNote: you may need to restart the kernel to use updated packages.
  Downloading geocoder-1.38.1-py2.py3-none-any.whl (98 kB)
Requirement already satisfied: requests in c:\users\tevin\anaconda3\lib\site-packages (from geocoder) (2.24.0)
Requirement already satisfied: click in c:\users\tevin\anaconda3\lib\site-packages (from geocoder) (7.1.2)
Collecting ratelim
  Downloading ratelim-0.1.6-py2.py3-none-any.whl (4.0 kB)
Requirement already satisfied: six in c:\users\tevin\anaconda3\lib\site-packages (from geocoder) (1.15.0)
Requirement already satisfied: future in c:\users\tevin\anaconda3\lib\site-packages (from geocoder) (0.18.2)
Requirement already satisfied: idna<3,>=2.5 in c:\users\tevin\anaconda3\lib\site-packages (from requests->geocoder) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\tevin\anaconda3\lib\site-packages (from requests->geocoder) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\tevin\anaconda3\lib\site-packages (from requests->geocoder) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\tevin\anaconda3\lib\site-packages (from requests->geocoder) (1.25.11)
Requirement already satisfied: decorator in c:\users\tevin\anaconda3\lib\site-packages (from ratelim->geocoder) (4.4.2)
Installing collected packages: ratelim, geocoder
Successfully installed geocoder-1.38.1 ratelim-0.1.6

#### 2.2 Import the library

In [72]:
import geocoder

#### 2.3 Import the CSV file

In [73]:
geo_data_url = "https://cocl.us/Geospatial_data"

geo_data = pd.read_csv(geo_data_url)

geo_data

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
..          ...        ...        ...
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

#### 2.4 Join the two data frames together

In [81]:
# First ensure that the row numbers match for both data frames

if df.shape[0] == geo_data.shape[0]: 
    print(" The two datasets match and can be joined")

 The two datasets match and can be joined

In [82]:
# use the postal code as the key linking the two datasets and join them based on that data set
complete_dataset = df.join(geo_data.set_index("Postal Code"), on="Postal Code", how="inner")
complete_dataset

,Postal Code,Borough,Neighbourhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494
...,...,...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",43.653654,-79.506944
99,M4Y,Downtown Toronto,Church and Wellesley,43.665860,-79.383160
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C...",43.662744,-79.321558
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu...",43.636258,-79.498509
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,...",43.628841,-79.520999

#### 2.5 Get the shape of the total dataset

In [83]:
print("The combined data frame has ", complete_dataset.shape[0], "rows and ", complete_dataset.shape[1], "columns")

The combined data frame has  103 rows and  5 columns

# This is the end of my attempt for Question 2